export const PRIMARY_COLOR='#F9FCE1'
export const PRIMARY_COLOR_DARK='#E9EDC9'
export const INPUT_COLOR='#D2E3C8'
export const BUTTON_COLOR='#C7E9B0'
export const SECOND_COLOR='#E5FDD1'
export const ERROR_COLOR='#FF0000'